services:
  db:
    image: postgres:15-alpine
    container_name: liveconnect-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: liveconnect
      # Ostavljamo trust da bude bez lozinke u DEV
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d liveconnect"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./liveconnect-backend
    container_name: liveconnect-backend-1
    environment:
      PORT: "4000"
      JWT_SECRET: "supersecret_dev_only_change_me"
      # KLJUČNO: u Docker mreži koristimo db:5432 (ne localhost:5433)
      DATABASE_URL: "postgresql://postgres@db:5432/liveconnect?schema=public"
      CORS_ORIGIN: "http://localhost:3000,http://localhost:8080"
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
